CREATE TABLE usertable (
key VARCHAR(100) NOT NULL,
field0 VARCHAR(100) NOT NULL,
field1 VARCHAR(100) NOT NULL,
field2 VARCHAR(100) NOT NULL,
field3 VARCHAR(100) NOT NULL,
field4 VARCHAR(100) NOT NULL,
field5 VARCHAR(100) NOT NULL,
field6 VARCHAR(100) NOT NULL,
field7 VARCHAR(100) NOT NULL,
field8 VARCHAR(100) NOT NULL,
field9 VARCHAR(100) NOT NULL,
);

PARTITION TABLE usertable ON COLUMN key;
CREATE INDEX key_idx ON usertable(key);

CREATE PROCEDURE INSERTUSER AS
INSERT INTO usertable VALUES (?,?,?,?,?,?,?,?,?,?,?);
PARTITION PROCEDURE INSERTUSER ON TABLE usertable COLUMN key;

CREATE PROCEDURE FROM CLASS SelectUser;
PARTITION PROCEDURE SelectUser ON TABLE usertable COLUMN key;

CREATE PROCEDURE FROM CLASS DeleteUser;
PARTITION PROCEDURE DeleteUser ON TABLE usertable COLUMN key;

CREATE PROCEDURE FROM CLASS UpdateUser;
PARTITION PROCEDURE UpdateUser ON TABLE usertable COLUMN key PARAMETER 10;

CREATE PROCEDURE FROM CLASS ScanUsers;

